language: php

php:
    - '7.1'

sudo: false

cache:
    directories:
        - "$HOME/.composer/cache"

install:
    - composer install --no-interaction --no-progress

script:
    - bin/phpunit

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar --access-token="86bd9078d28a29fca0a80e4998931db4abb845fe3b681dfd099a9dddd0f8bd71" code-coverage:upload --format=php-clover ./build/logs/clover.xml
