services:
    fluent.logger:
        class: Fluent\Logger\FluentLogger
        arguments: ['%fluent_handler.host%', '%fluent_handler.port%']

    monolog.handler.fluent:
        class: FluentHandlerBundle\Service\FluentHandlerService
        arguments: ['@fluent.logger']
        calls: 
            - [setChannel, ['%fluent_handler.channel%']]
